# Triangular, pentagonal, and hexagonal

#
#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#<table><tr><td>Triangle</td>
#<td> </td>
#<td>Tn=n(n+1)/2</td>
#<td> </td>
#<td>1, 3, 6, 10, 15, ...</td>
#</tr><tr><td>Pentagonal</td>
#<td> </td>
#<td>Pn=n(3n−1)/2</td>
#<td> </td>
#<td>1, 5, 12, 22, 35, ...</td>
#</tr><tr><td>Hexagonal</td>
#<td> </td>
#<td>Hn=n(2n−1)</td>
#<td> </td>
#<td>1, 6, 15, 28, 45, ...</td>
#</tr></table>It can be verified that T285 = P165 = H143 = 40755.
#Find the next triangle number that is also pentagonal and hexagonal.
#

import time

startTime = time.time()



print('Elapsed time: ' + str(time.time()-startTime))