# Cyclical figurate numbers

#
#Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:
#<table><tr><td>Triangle</td>
#<td> </td>
#<td>P3,n=n(n+1)/2</td>
#<td> </td>
#<td>1, 3, 6, 10, 15, ...</td>
#</tr><tr><td>Square</td>
#<td> </td>
#<td>P4,n=n2</td>
#<td> </td>
#<td>1, 4, 9, 16, 25, ...</td>
#</tr><tr><td>Pentagonal</td>
#<td> </td>
#<td>P5,n=n(3n−1)/2</td>
#<td> </td>
#<td>1, 5, 12, 22, 35, ...</td>
#</tr><tr><td>Hexagonal</td>
#<td> </td>
#<td>P6,n=n(2n−1)</td>
#<td> </td>
#<td>1, 6, 15, 28, 45, ...</td>
#</tr><tr><td>Heptagonal</td>
#<td> </td>
#<td>P7,n=n(5n−3)/2</td>
#<td> </td>
#<td>1, 7, 18, 34, 55, ...</td>
#</tr><tr><td>Octagonal</td>
#<td> </td>
#<td>P8,n=n(3n−2)</td>
#<td> </td>
#<td>1, 8, 21, 40, 65, ...</td>
#</tr></table>The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.
#<ol><li>The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).</li>
#<li>Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set.</li>
#<li>This is the only set of 4-digit numbers with this property.</li>
#</ol>Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.
#

import time

startTime = time.time()



print('Elapsed time: ' + str(time.time()-startTime))