# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pronunciation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('cmu', 'CMU'), ('hindic', 'Hindic')], max_length=20)),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pronunciation',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worddb.Word'),
        ),
    ]
