#!/usr/bin/env bash
#
# make the curl-able version of the course
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: December 13, 2025
# License: MIT


LINE_COLORS=(
	$'\e[48;5;160m'
	$'\e[48;5;202m'
	$'\e[48;5;214m'
)

TEXT_COLOR=$'\e[38;5;223m'
GREEN_COLOR=$'\e[38;5;120m'
RST=$'\e[0m'

C1=$TEXT_COLOR
C2=$GREEN_COLOR

WIDTH=80

cat <<-EOF



$C1         ┏┳┓┓     ┏┓       ┓      $C2 ┳┓   ┓   ┏┓   •   •     $C1 ┏┓
$C1          ┃ ┣┓┏┓  ┃ ┏┓┏┳┓┏┓┃┏┓╋┏┓ $C2 ┣┫┏┓┏┣┓  ┗┓┏┏┓┓┏┓╋┓┏┓┏┓ $C1 ┃ ┏┓┓┏┏┓┏┏┓
$C1          ┻ ┛┗┗   ┗┛┗┛┛┗┗┣┛┗┗ ┗┗  $C2 ┻┛┗┻┛┛┗  ┗┛┗┛ ┗┣┛┗┗┛┗┗┫ $C1 ┗┛┗┛┗┻┛ ┛┗
$C1                         ┛        $C2                ┛      ┛ $C1


EOF
echo -n "$C1"

items=(
	'7+ Hours'
	'60+ Sections'
	'Created by Dave Eddy'
	'https://course.ysap.sh'
)
# calculate padding to center justify it first (look for longest line)
longest=-1
for item in "${items[@]}"; do
	# center justify it
	len=${#item}
	if ((len > longest)); then
		longest=$len
	fi
done
pad=$(((WIDTH - longest) / 2))
for item in "${items[@]}"; do
	len=${#item}
	i=$(( pad + (longest - len) / 2))
	((i -= 2)) # i eyeballed this
	printf '%*s %s\n' "$i" ' ' "$item"
done

printf '\n\n'
for color in "${LINE_COLORS[@]}"; do
	printf '%s%s%*s%s\n' "$RST" "$color" "$WIDTH" ' ' "$RST"
done

echo
echo -n "$TEXT_COLOR"
printf '  %-61s %s\n' 'Bash Course' 'course.ysap.sh'
echo -n "$RST"
echo
